# MAIN base
baseURL = "https://apsho-hugo.netlify.app/"
languageCode = "en-us"
title = "Apsho | App landing template"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#features"
    weight = 2
[[menu.main]]
    name = "Pricing"
    url = "#pricing"
    weight = 3
[[menu.main]]
    name = "Testimonials"
    url = "#testimonials"
    weight = 4
[[menu.main]]
    name = "FAQ"
    url = "#faq"
    weight = 5

# Footer Sitemap
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "/privacy-policy"
    weight = 1
[[menu.sitemap]]
    name = "Terms of Service"
    url = "/terms-of-service"
    weight = 2

[params]

head = """
<!-- custom scripts -->
"""

# Header
logo = "images/logo.png"
signUpUrl = "/signup"
signUpLabel = "SIGN UP"
logInUrl = "/login"
logInLabel = "LOG IN"

# Footer
footerSubscribeTitle = "Get the latest app updates"
footerSubscribeDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
footerSubscribeButtonLabel = "SUBSCRIBE"
copyright = "©  <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a> {year}"

#contact
email = "help@staticmania.com"
